modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="more_babies"
version="${file.jarVersion}"
displayName="More Babies"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://curseforge.com/minecraft/mc-mods/more-babies"
logoFile="icon.png"
credits=""
authors="mammut53"
description='''Adds more babies!'''

[[dependencies.more_babies]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_babies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
