plugins {
    id "java"
    id "xyz.wagyourtail.unimined" version "1.4.2-SNAPSHOT"
}

group group
version version

base {
    archivesName = mod_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
}

sourceSets {
    fabric
    neoforge
}

repositories {
    unimined.neoForgedMaven()
    unimined.spongeMaven()
    unimined.modrinthMaven()
    unimined.wagYourMaven("releases")
}

unimined.minecraft(sourceSets.main) {
    version minecraft_version

    mappings {}

    accessWidener {
        accessWidener "${projectDir}/src/main/resources/${mod_id}.classtweaker"
    }

    if (sourceSet == sourceSets.main) {
        defaultRemapJar = false
    }

    runs {
        off = true
    }
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    fabric {
        loader fabric_loader
        accessWidener "${projectDir}/src/main/resources/${mod_id}.classtweaker"
    }

    defaultRemapJar = true

    runs {
        off = false

        config("client") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/fabric/client")
        }

        config("server") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/fabric/server")
        }
    }
}
/*
unimined.minecraft(sourceSets.neoforge) {
    combineWith(sourceSets.main)

    neoForge() {
        loader neoforge_version
        mixinConfig("${mod_id}.mixins.json", "${mod_id}-neoforge.mixins.json")
        accessTransformer aw2at("${projectDir}/src/main/resources/${mod_id}.classtweaker")
    }

    defaultRemapJar = true

    runs {
        off = false

        config("client") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/neoforge/client")
        }

        config("server") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/neoforge/server")
        }
    }
}*/

configurations {
    mainImplementation
}

dependencies {
    implementation "org.spongepowered:mixin:0.8.7-SNAPSHOT"
    implementation 'org.ow2.asm:asm:9.5'

    fabricModImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api}"
    fabricModImplementation "maven.modrinth:modmenu:${modmenu}"
}

processResources {
    inputs.property "version", version

    filesMatching("pack.mcmeta") {
        expand project.properties
    }
}

processFabricResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand project.properties
    }
}
/*
processNeoforgeResources {
    inputs.property "version", version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand project.properties
    }
}*/

tasks.withType(Jar).configureEach {
    from("LICENSE") {}
}

tasks.named("remapFabricJar") {
    archiveFileName = "${mod_name}-${version}-fabric+mc${minecraft_version}.jar"
}
/*
tasks.named("remapNeoforgeJar") {
    archiveFileName = "${mod_name}-${version}-neoforge+mc${minecraft_version}.jar"
}*/