plugins {
    id "java"
    id "xyz.wagyourtail.unimined" version "1.4.2-SNAPSHOT"
}

group group
version version

base {
    archivesName = mod_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
}

sourceSets {
    fabric
}

repositories {
    unimined.spongeMaven()
    unimined.modrinthMaven()
    unimined.wagYourMaven("releases")

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }

}

unimined.minecraft(sourceSets.main) {
    version minecraft_version

    mappings {}

    accessWidener {
        accessWidener "${projectDir}/src/main/resources/${mod_id}.classtweaker"
    }

    if (sourceSet == sourceSets.main) {
        defaultRemapJar = false
    }

    runs {
        off = true
    }
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    fabric {
        loader fabric_loader
        accessWidener "${projectDir}/src/main/resources/${mod_id}.classtweaker"
    }

    defaultRemapJar = true

    runs {
        off = false

        config("client") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"
            args += ["--quickPlaySingleplayer", "More Babies Test World 26_2"]

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/fabric/client")
        }

        config("server") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/fabric/server")
        }
    }
}

/*unimined.minecraft(sourceSets.neoforge) {
    combineWith(sourceSets.main)

    neoForge() {
        loader neoforge_version
        mixinConfig("${mod_id}.mixins.json", "${mod_id}-neoforge.mixins.json")
        // transformer via Fabric seems to not work do to the switch to classtweakers
        //accessTransformer aw2at("${projectDir}/src/main/resources/${mod_id}.classtweaker")
        accessTransformer "${projectDir}/src/neoforge/resources/META-INF/accesstransformer.cfg"
    }

    defaultRemapJar = true

    runs {
        off = false

        config("client") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/neoforge/client")
        }

        config("server") {
            jvmArgs += "-XX:+AllowEnhancedClassRedefinition"

            def mixinJar = configurations.runtimeClasspath.files.find { it.name.contains("mixin") }
            if (mixinJar != null) {
                jvmArgs += "-javaagent:${mixinJar.absolutePath}"
            }

            workingDir = file("$projectDir/run/neoforge/server")
        }
    }
}*/

configurations {
    mainImplementation
}

dependencies {
    implementation "org.spongepowered:mixin:0.8.7-SNAPSHOT"
    implementation 'org.ow2.asm:asm:9.5'
    // implementation "eu.midnightdust:midnightlib:${project.midnightlib_version}-fabric"

    fabricModImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api}"
    /*fabricModImplementation "maven.modrinth:modmenu:${modmenu}"
    fabricModImplementation "eu.midnightdust:midnightlib:${project.midnightlib_version}-fabric"
    fabricInclude "eu.midnightdust:midnightlib:${project.midnightlib_version}-fabric"

    neoforgeModImplementation "eu.midnightdust:midnightlib:${project.midnightlib_version}-neoforge"
    neoforgeInclude "eu.midnightdust:midnightlib:${project.midnightlib_version}-neoforge"*/
}

processResources {
    inputs.property "version", version

    filesMatching("pack.mcmeta") {
        expand project.properties
    }
}

processFabricResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand project.properties
    }
}
/*
processNeoforgeResources {
    inputs.property "version", version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand project.properties
    }
}*/

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from("LICENSE")
}

tasks.named("remapFabricJar") {
    archiveFileName = "${mod_name}-${version}-fabric+mc${minecraft_version}.jar"
}
/*
tasks.named("remapNeoforgeJar") {
    archiveFileName = "${mod_name}-${version}-neoforge+mc${minecraft_version}.jar"
}*/