#Project
version=3.1.0
project_group=io.github.mammut53.more_babies

#Mod
mod_author=mammut53
mod_id=more_babies
mod_name=More Babies

mod_description=Adds more baby mobs! Baby Blaze, Creeper, Enderman, Shulker and many more...
mod_homepage=https://modrinth.com/mod/more-babies
mod_sources=https://github.com/mammut53/more-babies
mod_issues=https://github.com/mammut53/more-babies/issues
mod_license=ARR

# Shared
minecraft_version=26.3-snapshot-7

# Fabric
fabric_loader=0.19.2
fabric_api=0.156.2+26.3
# modmenu=21.0.0-alpha.1

# NeoForge
# neoforge_version=0-beta

# Dependencies
# midnightlib_version=1.9.3+26.2

# Auth
unimined.auth.enabled=false
unimined.auth.username=myUsername
unimined.auth.storeCredentials=true
unimined.auth.encryptStoredCredentials=true

# Gradle Options
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
