modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/more-babies/forge_updates.json?neoforge=only"
displayURL="${mod_homepage}"
logoFile="assets/${mod_id}/icon.png"
credits=""
authors="${mod_author}"
description='''
${mod_description}
'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}-neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[26.1.0.1-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="midnightlib"
type="required"
versionRange="[1.9.3,)"
ordering="AFTER"
side="BOTH"